### ISSUE TITLE
"Guru meditation error!" When pressing select on NDS games

### ISSUE THREAD

**Issue by Nomelas** [Robz8/DSiMenuPlusPlus#193] opened 2018-09-08 20:20 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release - 2.0.2
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release - Beta, 6.10
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Pressing select on any nds game on any theme but Acekard should bring up a screen for custom settings for that particular game.

### Actual behaviour

Pressing select on any nds game on any theme but Acekard results in red top screen with "Guru meditation error!" message. Must return to 3ds home screen to exit

### Steps to reproduce

1. Be in either DSi, 3DS or R4 theme
2. Highlight NDS game
3. Press select

**Comment by Nomelas** [comment] 2018-09-08 21:43
To add, I am able to modify per-game settings with Acekard theme. (I've also tried deleting the game's ini, no change)

**Comment by Omnija** [comment] 2018-09-11 15:46
It also happens when changing the gamelist view to the style with out images.

**Comment by Robz8** [comment] 2018-09-11 18:35
The issue is referring to the one in the DSi, 3DS, and R4 theme, which have been fixed in v6.1.1.

**Closed by Robz8** 2018-09-11 18:35 UTC
Labels: bug
