### ISSUE TITLE
DSiMenu++ ends up on black screen without loading after DS/DSi boot screen on Old 3DS

### ISSUE THREAD

**Issue by Tatsu2993** [Robz8/DSiMenuPlusPlus#134] opened 2018-07-28 16:09 UTC
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [X]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[v 1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[v 5.3.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Boot into DSiMenu++ after DS/DSi Boot sequence.

### Actual behaviour

Get a black screen after DS/DSi boot sequence and the DSiMenu never loads. If a press any button during this state it goes back to the home-screen.

### Steps to reproduce

1. Copy the "_nds" and "boot.nds" to the root folder of the SD. Copy the cia files for the game booter, DSiMenu++  and the launcher to a folder for installing the cias on the SD.
2. Start up FBI cia installer. Install the DSiMenu++ cias, starting with the game booter, then the DSi Menu one, and lastly the launcher.
3. Start up the DSiMenu++ Launcher. Start DSiMenu++ after the Launcher is loaded up. Touch the screen after the DS/DSi boot sequence.

**Comment by AutoLiMax** [comment] 2018-07-29 20:58
I have this exact issue with the same set up as you. The only difference being I'm using an old 3DS XL.

**Comment by Tatsu2993** [comment] 2018-07-30 21:27
Just to add to the case, I just tried out using another SD and no luck. The SD was clean I just put the files of the DSiMenu on the SD. I even reinstalled the cias and nothing, same issue.

This is quite frustrating and saddening. Hope that Robz can help us out.

**Comment by Robz8** [comment] 2018-07-30 21:32
Sorry, I don't know what's causing this. :(

**Comment by Robz8** [comment] 2018-07-30 21:32
Can any of you try following this guide?: https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by Tatsu2993** [comment] 2018-07-30 21:34
Let me see what I can get with this. I will let you know in the next hours.

**Comment by Tatsu2993** [comment] 2018-07-30 21:44
Good news. I followed the guide and it runs flawlessly. Thanks, Robz. To the other guys, you should try with the method described in the guide. Thanks again Robz.

**Comment by AutoLiMax** [comment] 2018-08-02 20:06
This worked perfectly. You're a super star Robz8!

**Comment by NightYoshi370** [comment] 2018-09-06 02:58
Closing since the issue is resolved. I'll add the link to #important on the discord server

**Closed by NightYoshi370** 2018-09-06 02:58 UTC
